api_platform:
    title: 'OCHA API'
    description: 'The public OCHA API'
    version: 0.0.1
    show_webby: '%env(PLATFORM_SHOW_WEBBY)%'
    enable_profiler: '%env(PLATFORM_ENABLE_PROFILER)%'
    formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']
    swagger:
        api_keys:
            API-Key:
                name: API-KEY
                type: header
        swagger_ui_extra_configuration:
            defaultModelsExpandDepth: -1
    http_cache:
        invalidation:
            enabled: true
    defaults:
        pagination_items_per_page: 500
        cache_headers:
            max_age: 60
            shared_max_age: 60
            vary: ['Content-Type', 'Authorization', 'Origin']
