api_platform:
    title: 'OCHA API'
    description: 'This is a beta API that OCHA is testing to pull together key figures to power some of its own websites (e.g. unocha.org). It will not contain detailed data from each of the sources. If you are interested detailed data, we suggest you use the respective sources API. Questions: email support@unocha.org'
    version: 1.0.1
    show_webby: false
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    keep_legacy_inflector: false
    formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']
    swagger:
        api_keys:
            API-Key:
                name: API-KEY
                type: header
            APP-NAME:
                name: APP-NAME
                type: header
        swagger_ui_extra_configuration:
            defaultModelsExpandDepth: -1
    http_cache:
        invalidation:
            enabled: false
    defaults:
        pagination_items_per_page: 500
        cache_headers:
            max_age: 60
            shared_max_age: 60
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            skip_deprecated_exception_normalizers: true
