nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: true
        allow_origin: ['http://localhost:5678', '%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Credentials', 'Access-Control-Request-Headers', 'n8n-version']
        expose_headers: ['Link', 'Access-Control-Allow-Credentials']
        max_age: 3600
    paths:
        '^/': null
