when@dev:
    web_profiler:
        toolbar: '%env(bool:PLATFORM_ENABLE_PROFILER)%'
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: '%env(bool:PLATFORM_ENABLE_PROFILER)%'
        intercept_redirects: false

    framework:
        profiler: { collect: false }
