controllers:
    resource: ../src/Controller/
    type: attribute
api_platform:
    resource: .
    type: api_platform
    prefix: /api
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '/api'
        permanent: true
