controllers:
    resource: ../src/Controller/
    type: attribute
homepage:
    path: /
    controller: App\Page\HomePageController::home
api_home:
    path: /api
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '/api/v1'
        permanent: true
