# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\OpenApi\OpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@App\OpenApi\OpenApiFactory.inner' ]
        autoconfigure: false

    App\State\KeyFigures\KeyFiguresLimitByProviderStateProvider:
        arguments: [ '@api_platform.metadata.resource.metadata_collection_factory', '@doctrine', '@security.token_storage', !tagged_iterator { tag: 'api_platform.doctrine.orm.query_extension.collection', index_by: 'key' } ]

    App\State\KeyFigures\KeyFiguresPutStateProvider:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'

    App\State\User\RegisterStateProvider:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'

    App\EventListener\RequireServiceNameListener:
        decorates: api_platform.listener.request.read
        arguments: [ '@App\EventListener\RequireServiceNameListener.inner' ]

    App\EventListener\PutListener:
        decorates: api_platform.listener.request.read
        arguments: [ '@App\EventListener\PutListener.inner' ]

    App\OpenApi\AddAliases:
        decorates: api_platform.metadata.resource.metadata_collection_factory
        decoration_priority: 499
        arguments: [ '@App\OpenApi\AddAliases.inner' ]

    App\Serializer\KeyFigureSerializer:
        # By default .inner is passed as argument
        decorates: 'api_platform.serializer.normalizer.item'

    App\Serializer\OchaPresenceDenormalizer:
        tags:
            - { name: serializer.normalizer}

    App\Serializer\OchaPresenceExternalIdDenormalizer:
        tags:
            - { name: serializer.normalizer}

    App\Serializer\ExternalLookupDenormalizer:
        tags:
            - { name: serializer.normalizer}

    App\EventListener\DatabaseOnFlushListener:
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'onFlush'

    # JSON Filter
    App\Filter\JsonFilter:

    Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: ~

    # Custom Alice purger for version tables
    fidry_alice_data_fixtures.persistence.purger_factory.doctrine:
        class: App\Alice\Purger\VersionPurger
        arguments:
            - '@doctrine.orm.entity_manager'
